In [1]:
import numpy as np

In [ ]:
edit mode(연두색) : tab(자동완성), shift+tab(아규먼트<함수에대한 설명)
                    ,esc(커맨드모드 전환)

command mode(하늘색) : enter(edit mode),a(위에 셀추가),b(아래 셀추가),x(셀삭제),z(삭제취소)
                       ,o(결과값 접고펴기),M(해당셀 주석셀로 변경),Y(코드셀로 변경)
        
프린트 없이 출력은 jupyter 자체 스타일 적용

# 여기는 주석셀
## 테스트1
### 테스트 2
여기는<br>
테스트

In [2]:
a = 10
b = 20
a,b

(10, 20)

## 용어정리

### scalar : 상수값(10)
### vector(1차원) : [10,20,30]
### matrix(2차원) : [[10,20,30],[10,20,30]]
### 3차원 : [[[10,20,30],[10,20,30]],[[10,20,30],[10,20,30]]] 2x2x3


객체 : 속성 +메소드
객체.속성
객체.메소드()

In [7]:
my = [10,20,30]
print(type(my))

<class 'list'>


1. ndarray 생성방법

In [10]:
arr1 = np.array([10,20,30])
type(arr1)

numpy.ndarray

In [9]:
arr2  = np.array([[10,20,30],[10,20,30]])
arr2

array([[10, 20, 30],
       [10, 20, 30]])

2.ndarray 생성방법

In [11]:
arr3 = np.arange(1,11,1)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr4 = np.arange(1,11,2)
arr4

array([1, 3, 5, 7, 9])

3. ndarray 생성방법 

In [15]:
arr5 = np.random.randint(1,11,size = 5)
arr5

array([7, 6, 2, 9, 4])

In [16]:
arr6 = np.random.randint(1,11,size = (3,2))
arr6

array([[7, 2],
       [6, 5],
       [3, 5]])

In [17]:
np.random.rand(5) # 0~1 사이에 임의의 실수값반환

array([0.86587128, 0.29663587, 0.55505528, 0.8686618 , 0.75235391])

In [18]:
np.random.randn(5) # 표준정규분포(평균이0 편차1) 갯수가 많을수록

array([ 0.54879069, -1.28729167,  1.11586489,  0.77080192,  1.12772761])

In [19]:
np.random.randn(2,3)

array([[-1.66240211,  0.10209567, -0.39149747],
       [ 0.61606411, -0.22650267, -0.29153701]])

In [24]:
np.random.choice([1,2,3,4,5],3,replace = False)

array([2, 5, 1])

In [29]:
arr6 = np.arange(1,11)
np.random.shuffle(arr6)
arr6

array([10,  1,  7,  3,  2,  5,  8,  6,  9,  4])

4. ndarray 생성방법 

In [30]:
arr7 = np.int32([1,2,3,4,5])
# np.array([1,2,3,4,5],dtype = np.int32)

array([1, 2, 3, 4, 5])

In [31]:
np.float32()

0.0

In [33]:
np.array([1,2,3,4,5],dtype = np.str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.eye(3) #sparse 매트릭스(희소 행렬) one hot encoding

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.linspace(1,10) # 1~10 까지 간격이 동일하게 디폴트=50 개 생성

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
v,c = np.unique([1,2,3,2,3,42,3,3,2,3,2,4,5,1],return_counts=True) # 중복제거

In [49]:
for a,b in zip(v,c):
    print(a,b)

1 2
2 4
3 5
4 1
5 1
42 1
