In [1]:
import numpy as np

In [3]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

# 핵심 속성

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.size

5

In [6]:
arr.shape

(5,)

In [7]:
arr.ndim

1

In [9]:
arr1 = np.array([[11,22],[33,44],[55,66]])

In [10]:
arr1.shape # 형태 확인

(3, 2)

In [11]:
arr1.size

6

In [13]:
arr1.T # 3행2열 짜리를 2행 3열로 바꿔준다

array([[11, 33, 55],
       [22, 44, 66]])


# 형변환

In [15]:
arr = arr.astype(np.int64) # 인자에 적혀있는 타입으로 변환

In [16]:
arr

array([11, 22, 33, 44, 55], dtype=int64)

In [17]:
arr2 = np.array([1,2,3,4,5,6])
arr2

array([1, 2, 3, 4, 5, 6])

In [19]:
arr2.reshape(3,2) # arr2의 배열 형태를 바꿈

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
arr2 = arr2.reshape(2,-3) # 행값을 넣으면 알아서 적용됨