In [5]:
import numpy as np

In [6]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [8]:
arr[0]

11

# 인덱싱 

In [9]:
arr[[0,2,3]] # 복수개의 인덱스 선택(슬라이싱)

array([11, 33, 44])

## boolean indexing

In [10]:
arr[[True,True,False,True,True]] # True 값만 선택

array([11, 22, 44, 55])

## slicing(슬라이싱)

In [12]:
# [시작:끝:증가치]
arr[1:4] # 1<=idx<4

array([22, 33, 44])

In [13]:
arr[:4]

array([11, 22, 33, 44])

In [14]:
arr[:-1] # 0<=inx<-1

array([11, 22, 33, 44])

In [17]:
arr[-1:-4:-1] # -1자리부터 -4자리까지 -1 만큼 커지면서 = 거꾸로 센다

array([55, 44, 33])

# 연산(산술,관계,논리)
### element wise(요소별 연산)

In [18]:
arr+2

array([13, 24, 35, 46, 57])

In [19]:
arr*2

array([ 22,  44,  66,  88, 110])

In [20]:
arr1= np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [21]:
arr+arr1

array([12, 24, 36, 48, 60])

In [23]:
#연봉데이터가 있을때 각연봉에 대한
# 세금 3.3을제한 실수령액을 구하시요
salary = np.array( [1000,2000,3000,4000,5000])
salary*0.967

array([ 967., 1934., 2901., 3868., 4835.])

## 관계 연산자

In [25]:
arr>30

array([False, False,  True,  True,  True])

In [26]:
#arr[[False, False,  True,  True,  True]]
arr[arr>30]

array([33, 44, 55])

In [28]:
arr==44

array([False, False, False,  True, False])

In [29]:
# 논리 연산자 
# and ==> &, or ==> |, not ==> ~

In [32]:
(arr ==11) | (arr==55)

array([ True, False, False, False,  True])

In [31]:
arr[(arr ==11) | (arr==55)]

array([11, 55])

In [36]:
arr[(arr>20) & (arr<50)]

array([22, 33, 44])

In [38]:
~((arr ==11) | (arr==55)) # not연산 ~((T)|(F)=T) = F

array([False,  True,  True,  True, False])

In [39]:
arr[~((arr ==11) | (arr==55))]

array([22, 33, 44])

In [70]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황','철이임'])
name

array(['홍길동', '김철수', '임꺽정', '김철이', '이황', '철이임'], dtype='<U3')

In [71]:
[n for n in name if '철'in n]


['김철수', '김철이', '철이임']

In [73]:
arr[arr>35]

array([44, 55])