In [1]:
import numpy as np

# 추가

In [25]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [26]:
arr = np.append(arr,[100,200])

In [4]:
np.insert(arr,1,[1,2])

array([11,  1,  2, 22, 33, 44, 55])

# 수정

In [27]:
arr[0]=111

In [28]:
arr[1:3] = [222,333]

In [29]:
arr[3:5] = arr[3:5]*2

In [30]:
arr

array([111, 222, 333,  88, 110, 100, 200])

In [31]:
# 200보다 큰데이터에 대해 기존값에 
# 2를 더한것으로 수정하시오
arr[arr>200] = arr[arr>200]+2

In [41]:
arr

array([111, 224, 335,  46,  57, 100, 200])

# 삭제

In [33]:
np.delete(arr,[0,2])

array([224,  88, 110, 100, 200])

In [37]:
np.where(arr<100)

(array([3, 4], dtype=int64),)

In [42]:
# 100이상인 값을 삭제하시오
np.delete(arr,np.where(arr>=100))

array([46, 57])

# 조건별 데이터 연산 

In [45]:
np.where(arr>=100,'A','B') # 참일경우 A 거짓일경우 B로 출력됨

array(['A', 'A', 'A', 'B', 'B', 'A', 'A'], dtype='<U1')

In [44]:
# 다중 조건인 경우 select와 조건을 변수에 넣어서 다중으로 검색
conList = [arr>200,arr>100,arr>0]
choiceList = ['A','B','C']
np.select(conList,choiceList)

array(['B', 'A', 'A', 'C', 'C', 'C', 'B'], dtype='<U11')

# 정렬

In [46]:
np.sort(arr)

array([ 46,  57, 100, 111, 200, 224, 335])

In [47]:
np.sort(arr)[-1::-1] # 내림차순으로 변경

array([335, 224, 200, 111, 100,  57,  46])

In [50]:
np.argsort(arr)  # arg 가 붙으면 인덱스로 반환

array([3, 4, 5, 0, 6, 1, 2], dtype=int64)

In [51]:
arr[np.argsort(arr)] # 인덱스를 받아서 출력

array([ 46,  57, 100, 111, 200, 224, 335])

In [52]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])

array([-1,  1, -1,  1, -1])

In [54]:
np.char.find(name,'철') # 원하는 값이 없으면 -1 있으면 그 값의 인덱스값을 보여줌
name[np.char.find(name,'철')>=0]

array(['김철수', '김철이'], dtype='<U3')

In [55]:
# https://numpy.org/doc/stable/reference/routines.char.html