In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

ndarray객체의 멤버함수 + np의함수
<br>
np의 함수

In [3]:
arr.sum()

165

In [5]:
np.sum(arr)

165

In [6]:
arr.mean()

33.0

In [7]:
np.mean(arr)

33.0

In [9]:
arr.max() # np.max(arr)

55

In [10]:
arr.argmax() # 최대값의 인덱스 

4

In [12]:
arr.argmin() # 최소값의 인덱스

0

In [13]:
arr.std() # 표준편차 np.std(arr)

15.556349186104045

In [15]:
np.median(arr) # 중앙값은 멤버 함수가 없음 짝수면 중앙인덱스 2개를 더해서 2로나눈값

33.0

In [18]:
np.quantile(arr,0.25) # 데이터를 정렬했을때 몇% 의 값

22.0

In [21]:
np.percentile(arr,[25,50,75]) # 위와 같은데 소수좀표현 차이

array([22., 33., 44.])

## 연습문제

In [23]:
kor = np.array([60,55,70,30,20,90])

1. 국어점수가 가장큰값을 구하시오
2. 국어점수가 80점 이상인 값을 구하시오

In [25]:
kor.max()

90

In [28]:
kor[kor>=80]

array([90])

3. 국어점수가 50점이상 80이하인 값을 구하시요
4. 국어점수의 평균을 구하시요.
5. 국어점수의 총합을 구하시요.
6. 국어점수가 40점이하인 데이터를 삭제하시요
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하시요.
8. 국어점수 top5를 구하시요
9. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
아래와 같이 출력하시요

60 '불합격'
55 '불합격'
...

In [30]:
# 3
kor[(kor>=50) & (kor<=80)]

array([60, 55, 70])

In [31]:
# 4
kor.mean()

54.166666666666664

In [32]:
# 5
kor.sum()

325

In [35]:
# 6
np.delete(kor,np.where(kor<=40))

array([60, 55, 70, 90])

In [37]:
# 7
kor[kor>=50]*1.1

array([66. , 60.5, 77. , 99. ])

In [60]:
# 8
np.sort(kor)[-1:-6:-1]


array([90, 70, 60, 55, 30])

In [48]:
seven =[kor>=70,kor<70]
conc = ['합격','불합격']
a = np.select(seven,conc)

In [52]:
np.where(kor>=70,'합격','불합격')

array(['불합격', '불합격', '불합격', '불합격', '합격', '합격'], dtype='<U3')

In [55]:
for s,r in zip(kor,np.where(kor>=70,'합격','불합격')):
    print(s,r)

20 불합격
30 불합격
55 불합격
60 불합격
70 합격
90 합격
